#!/bin/bash
# by Damien Berry
#
#                     GNU GENERAL PUBLIC LICENSE
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
DateKaamelott=1606258800         #date -d "2020-11-25 00:00:00" +%s # https://github.com/berrydamien/kaamelott-motd/issues/2 
DateActuelle=$(date +%s)
Secondes=$((DateKaamelott - DateActuelle))
if [ "$Secondes" -gt "0" ]; then
    echo -e "\nBientôt, Arthur sera de nouveau un héros ... $((Secondes/(3600*24))) jours, $(( (Secondes/3600)%24 )) heures, $(( (Secondes/60)%60 )) minutes et $((Secondes%60 )) secondes."
else
    echo -e "\nMaintenant, Arthur est de nouveau un héros ... et c'est au cinéma !!"
fi
